/**
 * PDF File Generation Script
 *
 * Since we cannot create binary files directly, here are the instructions
 * to create your PDF file manually:
 *
 * Method 1: Use the sample content provided
 * Method 2: Download a sample PDF from online
 * Method 3: Create your own PDF using any PDF creator
 */

// Sample PDF content that you can convert to PDF
export const SAMPLE_RESUME_CONTENT = `
Pintu Kumar
Full-Stack Developer

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

CONTACT INFORMATION
📧 Email: mrkumarrr12@gmail.com
📱 Phone: (+91) 80 8401 6480 
🔗 LinkedIn: linkedin.com/in/pintu-kumar-12x
💻 GitHub: github.com/Pintu-Kumar-1709
📍 Location: Bhopal Madhya Pradesh, India

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

PROFESSIONAL SUMMARY

Passionate Full-Stack Developer with 1+ years of expertise in React ecosystem, Next.js,Redux
and modern web technologies. Experienced in building scalable applications with Spring Boot, 
microservices architecture, and cloud deployment. Strong background in both frontend and 
backend development with a focus on clean code and best practices.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

WORK EXPERIENCE

🏢  FULL-STACK DEVELOPER
Independent Projects. | September 2025 - December 2025 | Bhopal City, Madhya Pradesh | India

• Led development of microservices architecture using  React
• Implemented CI/CD pipelines reducing deployment time by 70%
• Mentored 3 junior developers and conducted regular code reviews
• Architected scalable solutions serving 100,000+ daily active users
• Collaborated with cross-functional teams to deliver features on time

Technologies:  React, Next.js, Redux , Vercel , Github

🏢 FRONTEND DEVELOPER
Independent Projects. | January 2024 - February 2024 | Bhopal City, Madhya Pradesh | India

• Developed responsive web applications using React and TypeScript
• Improved application performance by 40% through code optimization
• Collaborated with UI/UX team to implement pixel-perfect designs
• Integrated RESTful APIs and implemented efficient state management
• Participated in agile development processes and sprint planning

Technologies: React, TypeScript, Redux, TailwindCSS, Auth.js,Framer-motion 



EDUCATION

🎓 BACHELOR OF COMPUTER SCIENCE
Patel College of Science & Technology, Bhopal (Madhya Pradesh) | August 2022 - Present
GPA: 7.8/10.0 | Bhopal, Madhya Pradesh | India

Achievements:
• Recognizes the Best Student in College
• Best Final Year Project Award - "ZestCo Grocery Website with AI Recommendations"
• Dean's List for 6 consecutive semesters
• Active member of Programming Club and Computer Science Society

Relevant Coursework:
• Data Structures and Algorithms
• Database Management Systems
• Software Engineering
• Web Development
• Computer Networks
• Machine Learning Fundamentals

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

TECHNICAL SKILLS

💻 BACKEND DEVELOPMENT
• Node.js (95%) - Express.js, Next.js, Backend Architecture
• Database (90%) -  MongoDB, SQL, MySql
• API Development (92%) - REST, GraphQL, Microservices

🎨 FRONTEND DEVELOPMENT  
• React (88%) - Hooks, Context API, Redux, Next.js
• JavaScript/TypeScript (90%) - ES6+, Modern JS
• CSS Frameworks (92%) - TailwindCSS, Bootstrap, ShadCn UI, SCSS, Styled Components

☁️ DEVOPS & TOOLS
• Cloud Platforms (75%) - Vercel, Render, Docker(Develop and TroubleShoot), 
• Version Control (95%) - Git, GitHub
• CI/CD (80%) -  GitHub Actions, Docker(Develop and TroubleShoot)

🛠️ SOFT SKILLS
• Leadership & Team Management
• Problem Solving & Critical Thinking
• Effective Communication
• Project Management
• Mentoring & Knowledge Sharing

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━



LANGUAGES

🌐 Hindi + mother's tongue: Native
🌐 English: Professional Working Proficiency 

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

INTERESTS & ACTIVITIES


• News - Exploring news 
• Photography & Videography - Creating content for tech tutorials
• Gaming & Game Development - Hobby game development using Unity
• Traveling & Cultural Exchange - Exploring new cultures and technologies

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

REFERENCES

Available upon request

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Generated by KumarrR Exhibition - Professional Resume Template
Visit: https://github.com/Pintu-Kumar-1709 | Contact: mrkumarrr12@gmail.com
`;

// Function to download the sample content as text file
export const downloadSampleResume = () => {
  const blob = new Blob([SAMPLE_RESUME_CONTENT], {
    type: "text/plain;charset=utf-8",
  });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = "kumarrR_Resume_Sample.txt";
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

// Instructions for creating the PDF
export const PDF_CREATION_INSTRUCTIONS = [
  {
    step: 1,
    title: "Download Sample Content",
    description: "Download the sample resume content as a text file",
    action: "Click the download button to get the sample text file",
  },
  {
    step: 2,
    title: "Convert to PDF",
    description: "Use any of these online tools to convert the text to PDF:",
    options: [
      {
        name: "SmallPDF",
        url: "https://smallpdf.com/txt-to-pdf",
        description: "Simple and clean converter",
      },
      {
        name: "ILovePDF",
        url: "https://www.ilovepdf.com/txt_to_pdf",
        description: "Professional PDF tools",
      },
      {
        name: "PDF24",
        url: "https://tools.pdf24.org/en/txt-to-pdf",
        description: "Free online converter",
      },
      {
        name: "ConvertIO",
        url: "https://convertio.co/txt-pdf/",
        description: "Advanced conversion options",
      },
    ],
  },
  {
    step: 3,
    title: "Customize Your PDF",
    description: "Before converting, you can:",
    actions: [
      "Update personal information with your details",
      "Add or modify work experience sections",
      "Update skills and certifications",
      "Add your actual contact information",
      "Customize the design and formatting",
    ],
  },
  {
    step: 4,
    title: "Save as kumarrR_Resume.pdf",
    description: "Save the generated PDF with the exact filename",
    important: "File must be named exactly: kumarrR_Resume.pdf",
  },
  {
    step: 5,
    title: "Place in Public Folder",
    description: "Move the PDF to the correct location",
    path: "public/documents/kumarrR_Resume.pdf",
    note: "This path is required for the PDF viewer to work correctly",
  },
];
